### ISSUE TITLE
Plugin compiling failed

### ISSUE THREAD

**Issue by schneidermatic** [kensiprell/grails-drools#2]
Hi Ken, 
I have some problems to compile the grails-drools plugin. The compiling throws the following exception:
| Loading Grails 2.4.5
| Configuring classpath
| Error Error executing script Compile: null
java.lang.NullPointerException
	at java.lang.reflect.Array.getLength(Native Method)
	at org.codehaus.groovy.util.ArrayIterator.<init>(ArrayIterator.java:29)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.findAll(DefaultGroovyMethods.java:3320)
	at grails.util.PluginBuildSettings.addPluginScopeInfoForDirAndInfo(PluginBuildSettings.groovy:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:149)
	at grails.util.PluginBuildSettings.registerPluginZipWithScope(PluginBuildSettings.groovy:170)
	at grails.util.PluginBuildSettings.populateSourceDirectories(PluginBuildSettings.groovy:157)
	at grails.util.PluginBuildSettings.this$2$populateSourceDirectories(PluginBuildSettings.groovy)
	at grails.util.PluginBuildSettings$this$2$populateSourceDirectories.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:145)
	at grails.util.PluginBuildSettings.<init>(PluginBuildSettings.groovy:116)
	at grails.util.PluginBuildSettings.<init>(PluginBuildSettings.groovy:102)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:190)
	at org.codehaus.groovy.grails.plugins.GrailsPluginUtils.newPluginBuildSettings(GrailsPluginUtils.groovy:116)
	at org.codehaus.groovy.grails.plugins.GrailsPluginUtils$newPluginBuildSettings.callStatic(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:53)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:157)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:165)
	at org.codehaus.groovy.grails.plugins.GrailsPluginUtils.getPluginBuildSettings(GrailsPluginUtils.groovy:125)
	at org.codehaus.groovy.grails.cli.api.BaseSettingsApi.<init>(BaseSettingsApi.java:99)
	at org.codehaus.groovy.grails.cli.support.ScriptBindingInitializer.initBinding(ScriptBindingInitializer.java:206)
	at org.codehaus.groovy.grails.cli.support.ScriptBindingInitializer.initBinding(ScriptBindingInitializer.java:100)
	at org.codehaus.groovy.grails.cli.GrailsScriptRunner.executeScriptFile(GrailsScriptRunner.java:567)
	at org.codehaus.groovy.grails.cli.GrailsScriptRunner.executeScriptWithCaching(GrailsScriptRunner.java:472)
	at org.codehaus.groovy.grails.cli.GrailsScriptRunner.callPluginOrGrailsScript(GrailsScriptRunner.java:416)
	at org.codehaus.groovy.grails.cli.GrailsScriptRunner.executeCommand(GrailsScriptRunner.java:380)
	at org.codehaus.groovy.grails.cli.GrailsScriptRunner.main(GrailsScriptRunner.java:226)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.grails.cli.support.GrailsStarter.rootLoader(GrailsStarter.java:236)
	at org.codehaus.groovy.grails.cli.support.GrailsStarter.main(GrailsStarter.java:264)
| Error Error executing script Compile: null

Any idea?

**Comment by schneidermatic** [comment]
Sorry, was my mistake. Everything works as expected.

**Comment by kensiprell** [comment]
Markus,

Did the breaking changes cause you any major problems?

Ken

**Comment by schneidermatic** [comment]
Ken,

all tests are passed successfully - don't know if that's the whole truth ;)
but I see the following errors on the console:

| Error Error loading event script from file [/opt/local/dev/lab/grails/drools/grails-drools-tester/test/grails-drools-sample/target/work/plugins/drools-1.0.0/scripts/_Events.groovy] No such property: droolsPluginDir for class: _Events (Use --stacktrace to see the full trace)
| Running Grails application
| Error Error loading event script from file [/opt/local/dev/lab/grails/drools/grails-drools-tester/test/grails-drools-sample/target/work/plugins/drools-1.0.0/scripts/_Events.groovy] No such property: droolsPluginDir for class: _Events (Use --stacktrace to see the full trace)

and before 'drools.sh' has finished there occurs the following exception:
tester/test/grails-drools-sample/target/test-reports
| Error Exception in thread "Thread-5" 
| Error java.lang.IllegalStateException: Shutdown in progress
| Error 	at java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:66)
| Error 	at java.lang.Runtime.addShutdownHook(Runtime.java:211)
| Error 	at org.codehaus.groovy.runtime.DefaultGroovyMethods.addShutdownHook(DefaultGroovyMethods.java:492)
| Error 	at org.grails.plugins.tomcat.fork.ForkedTomcatServer$_startSecure_closure6.doCall(ForkedTomcatServer.groovy:172)
| Error 	at org.grails.plugins.tomcat.fork.ForkedTomcatServer$_startSecure_closure6.call(ForkedTomcatServer.groovy)
| Error 	at groovy.lang.Closure.run(Closure.java:504)
| Error 	at org.grails.plugins.tomcat.fork.ForkedTomcatServer$_startSecure_closure6.run(ForkedTomcatServer.groovy)
| Error 	at java.lang.Thread.run(Thread.java:745)

-markus

**Comment by kensiprell** [comment]
Markus, I saw those errors as well, but they only appear when running the drools.sh test script. If you run `grails test-app functional:`, the errors don't appear. However, I will take another look.

**Comment by kensiprell** [comment]
Moved to https://github.com/kensiprell/grails-plugin-test-script/issues/2.
