### ISSUE TITLE
RunTimeException (Problem defining class)

### ISSUE THREAD

**Issue by lvazquezt** [kensiprell/grails-drools#7]
This might be a Grails issue but only happens since I use the Drools plugin.

I recently started the migration of my Drools project to integrate it with one in Grails. I get error during compilation time. Then the application works but it is annoying and I don't know if it is covering some deeper issue.
I have the following classes

Person.groovy
```
class Person extends AFact {
    Integer personId
    Date dateOfBirth
}
```
Member.groovy
```
class Member extends PersonDatedFact {

  Date date1 
  Date date2
  Date date3
 Member(Person person, Date date, SingleDatedFact startDate = null) {
    super(date, person, eventStart)
    this.date1= date
    this.date2 = date
    this.date3 = date
  }
...
}
```
Marriage.groovy
```
class Marriage extends SingleDatedFact {
    Person member
    Person spouse

    Marriage(Person member, Person spouse, Date date) {
        super(date)
        this.member = member
        this.spouse = spouse
    }
...
}
```
My rule file
```
import package.*
import package.facts.*
import package.validation.*
dialect  "mvel"

rule "myRule"
when
    p : Person()
    m : Marriage(member == p)

then
    insert(new ValidationError("Wrong!"));
end
```

This generates a big error trace during compilation (complete at the end), being the most interesting line this one:

java.lang.NoClassDefFoundError: package/member__I (wrong name: package/Member__I)

I am not making any call to the class Member. If I write my rule like 
```
rule "myRule"
when
    p : Person()
    m : Marriage(spouse== p)

then
    insert(new ValidationError("Wrong!"));
end
```

It doesn't throw any error.

I have to say that the application works anyway, but with the almost 200 rules I have, the stack trace becomes unmanageable when running the application. This didn't happen when using Drools with Java and Maven.

```
Error |
java.lang.RuntimeException: Reloading agent exited via exception, please raise a jira
Error |
	at org.springsource.loaded.agent.ClassPreProcessorAgentAdapter.transform(ClassPreProcessorAgentAdapter.java:104)
Error |
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
Error |
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
Error |
	at java.lang.ClassLoader.defineClass1(Native Method)
Error |
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
Error |
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
Error |
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
Error |
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
Error |
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
Error |
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
Error |
	at java.security.AccessController.doPrivileged(Native Method)
Error |
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
Error |
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
Error |
	at java.lang.ClassLoader.loadClass(ClassLoader.java:412)
Error |
	at org.grails.plugins.tomcat.ParentDelegatingClassLoader.loadClass(ParentDelegatingClassLoader.java)
Error |
	at java.lang.ClassLoader.loadClass(ClassLoader.java:412)
Error |
	at org.drools.core.common.ProjectClassLoader.internalLoadClass(ProjectClassLoader.java:144)
Error |
	at org.drools.core.common.ProjectClassLoader.loadClass(ProjectClassLoader.java:124)
Error |
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
Error |
	at java.lang.Class.forName0(Native Method)
Error |
	at java.lang.Class.forName(Class.java:274)
Error |
	at org.mvel2.ParserConfiguration.checkForDynamicImport(ParserConfiguration.java:163)
Error |
	at org.mvel2.ParserConfiguration.hasImport(ParserConfiguration.java:191)
Error |
	at org.mvel2.ParserContext.hasImport(ParserContext.java:373)
Error |
	at org.mvel2.compiler.AbstractParser.createPropertyToken(AbstractParser.java:1395)
Error |
	at org.mvel2.compiler.AbstractParser.nextToken(AbstractParser.java:899)
Error |
	at org.mvel2.compiler.ExpressionCompiler._compile(ExpressionCompiler.java:122)
Error |
	at org.mvel2.compiler.ExpressionCompiler.compile(ExpressionCompiler.java:63)
Error |
	at org.mvel2.MVEL.analysisCompile(MVEL.java:670)
Error |
	at org.mvel2.MVEL.analysisCompile(MVEL.java:674)
Error |
	at org.drools.compiler.rule.builder.PatternBuilder.setInputs(PatternBuilder.java:1151)
Error |
	at org.drools.compiler.rule.builder.PatternBuilder.getExprBindings(PatternBuilder.java:843)
Error |
	at org.drools.compiler.rule.builder.PatternBuilder.buildRelationalExpression(PatternBuilder.java:830)
Error |
	at org.drools.compiler.rule.builder.PatternBuilder.buildExpression(PatternBuilder.java:759)
Error |
	at org.drools.compiler.rule.builder.PatternBuilder.buildCcdDescr(PatternBuilder.java:743)
Error |
	at org.drools.compiler.rule.builder.PatternBuilder.build(PatternBuilder.java:694)
Error |
	at org.drools.compiler.rule.builder.PatternBuilder.processConstraintsAndBinds(PatternBuilder.java:548)
Error |
	at org.drools.compiler.rule.builder.PatternBuilder.build(PatternBuilder.java:321)
Error |
	at org.drools.compiler.rule.builder.PatternBuilder.build(PatternBuilder.java:140)
Error |
	at org.drools.compiler.rule.builder.GroupElementBuilder.build(GroupElementBuilder.java:66)
Error |
	at org.drools.compiler.rule.builder.RuleBuilder.build(RuleBuilder.java:98)
Error |
	at org.drools.compiler.builder.impl.KnowledgeBuilderImpl.addRule(KnowledgeBuilderImpl.java:1715)
Error |
	at org.drools.compiler.builder.impl.KnowledgeBuilderImpl.compileRules(KnowledgeBuilderImpl.java:1021)
Error |
	at org.drools.compiler.builder.impl.KnowledgeBuilderImpl.compileAllRules(KnowledgeBuilderImpl.java:899)
Error |
	at org.drools.compiler.builder.impl.CompositeKnowledgeBuilderImpl.buildRules(CompositeKnowledgeBuilderImpl.java:301)
Error |
	at org.drools.compiler.builder.impl.CompositeKnowledgeBuilderImpl.buildPackages(CompositeKnowledgeBuilderImpl.java:107)
Error |
	at org.drools.compiler.builder.impl.CompositeKnowledgeBuilderImpl.build(CompositeKnowledgeBuilderImpl.java:91)
Error |
	at org.drools.compiler.kie.builder.impl.AbstractKieModule.buildKnowledgePackages(AbstractKieModule.java:223)
Error |
	at org.drools.compiler.kie.builder.impl.KieContainerImpl.createKieBase(KieContainerImpl.java:429)
Error |
	at org.drools.compiler.kie.builder.impl.KieContainerImpl.getKieBase(KieContainerImpl.java:392)
Error |
	at org.kie.spring.KieObjectsResolver.resolveKBase(KieObjectsResolver.java:33)
Error |
	at org.kie.spring.factorybeans.KBaseFactoryBean.afterPropertiesSet(KBaseFactoryBean.java:162)
Error |
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1571)
Error |
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1509)
Error |
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:521)
Error |
	at org.codehaus.groovy.grails.commons.spring.ReloadAwareAutowireCapableBeanFactory.doCreateBean(ReloadAwareAutowireCapableBeanFactory.java:127)
Error |
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
Error |
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:296)
Error |
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
Error |
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:293)
Error |
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
Error |
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:328)
Error |
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
Error |
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1417)
Error |
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1158)
Error |
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
Error |
	at org.codehaus.groovy.grails.commons.spring.ReloadAwareAutowireCapableBeanFactory.doCreateBean(ReloadAwareAutowireCapableBeanFactory.java:127)
Error |
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
Error |
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:296)
Error |
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
Error |
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:293)
Error |
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
Error |
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:615)
Error |
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:932)
Error |
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479)
Error |
	at org.codehaus.groovy.grails.commons.spring.DefaultRuntimeSpringConfiguration.getApplicationContext(DefaultRuntimeSpringConfiguration.java:156)
Error |
	at org.codehaus.groovy.grails.commons.spring.GrailsRuntimeConfigurator.configure(GrailsRuntimeConfigurator.java:169)
Error |
	at org.codehaus.groovy.grails.commons.spring.GrailsRuntimeConfigurator.configure(GrailsRuntimeConfigurator.java:127)
Error |
	at org.codehaus.groovy.grails.web.context.GrailsConfigUtils.configureWebApplicationContext(GrailsConfigUtils.java:122)
Error |
	at org.codehaus.groovy.grails.web.context.GrailsContextLoader.initWebApplicationContext(GrailsContextLoader.java:108)
Error |
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
Error |
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4973)
Error |
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5467)
Error |
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
Error |
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
Error |
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
Error |
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
Error |
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
Error |
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
Error |
	at java.lang.Thread.run(Thread.java:745)
Error |
Caused by: org.springsource.loaded.ReloadException: Problem defining class package.member__I
Error |
	at org.springsource.loaded.TypeRegistry.defineClass(TypeRegistry.java:1119)
Error |
	at org.springsource.loaded.ReloadableType.rewriteCallSitesAndDefine(ReloadableType.java:830)
Error |
	at org.springsource.loaded.ReloadableType.<init>(ReloadableType.java:155)
Error |
	at org.springsource.loaded.TypeRegistry.addType(TypeRegistry.java:926)
Error |
	at org.springsource.loaded.agent.SpringLoadedPreProcessor.preProcess(SpringLoadedPreProcessor.java:298)
Error |
	at org.springsource.loaded.agent.ClassPreProcessorAgentAdapter.transform(ClassPreProcessorAgentAdapter.java:102)
Error |
	... 89 more
Error |
Caused by: java.lang.reflect.InvocationTargetException
Error |
	at sun.reflect.GeneratedMethodAccessor121.invoke(Unknown Source)
Error |
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error |
	at java.lang.reflect.Method.invoke(Method.java:606)
Error |
	at org.springsource.loaded.TypeRegistry.defineClass(TypeRegistry.java:1114)
Error |
	... 94 more
Error |
Caused by: java.lang.NoClassDefFoundError: package/member__I (wrong name: package/Member__I)
Error |
	at java.lang.ClassLoader.defineClass1(Native Method)
Error |
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
Error |
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
Error |
	... 98 more
```

**Comment by kensiprell** [comment]
I'm neither a Drools nor a Grails expert, but I'll try to help.

- What version of Grails and the plugin are you using?

- You say the errors are generated during compilation, but the stacktrace looks like runtime errors. Do the errors also happen at compile time?

- I'm puzzled by `java.lang.NoClassDefFoundError: package/member__I (wrong name: package/Member__I)`. Does your Member.groovy class start with `package package`? The two underscores and the I should be a clue as to where it's looking.

- What happens when you comment out `dialect "mvel"` in the rule that generates the error?

- Were the domain classes in an existing Grails application, or did you migrate them from Java?

- If the errors appear at runtime, how are you inserting the facts and triggering the rules, for example, are you using `DroolsService`?

Ken

**Comment by lvazquezt** [comment]
Hello,
* I am using grails 2.3.11 and 1.0.1 for the plugin
* I just realize it happens after 'Running Grails application' message, but before it says that the server is running. That got me confused but I guess is runtime (even when there is no method, service or anything calling the Drools engine at this point)
* I changed the name of my package for 'package' in the stacktrace  but it basically gives the full path 'package/subpackage/subpackage/class__I'. I have no class that ends with underscore, two underscores and I or anything similar.
*The same
*They were written in Groovy but it wasn't a Grails application. It is a standalone application and we want to move the logic to a web based one. Should they be proper Domain Classes? I just have them in Sources:Groovy.
* I get all those errors but it actually works fine.

```groovy
public ResultingFacts insertAndFireAll(ArrayList<Objects> facts) {

        ResultingFacts resultingFacts = new ResultingFacts()
        try {
            ruleTracer = new RuleTracer()
            statefulSession2012.setGlobal("ruleTracer", ruleTracer)
            statefulSession2012.addEventListener(new CustomAgendaEventListener())


            facts.each { Object fact -> statefulSession2012.insert(fact) }
            statefulSession2012.fireAllRules()
...
}
```

Thanks for your help,
Lino

**Comment by kensiprell** [comment]
Lino,

If your facts are persisted in a database, they should definitely be in `grails-app/domain`. 

How exactly are you using the plugin, only to manage the Drools dependencies? Based on your comments so far that's all I see. If that's the case, I would simply add the [Drools dependencies](https://github.com/kensiprell/grails-drools/blob/master/grails-app/conf/BuildConfig.groovy#L19-L88) to your Grails applications and use your existing code. If you don't want to take advantage of the following items the plugin offers, there's really no use for it:

* [drools-context.xml](https://github.com/kensiprell/grails-drools/blob/master/grails-app/conf/drools-context.xml)

* [DroolsConfig.groovy](https://github.com/kensiprell/grails-drools/blob/master/src/templates/conf/DroolsConfig.groovy)

* [DroolsService.groovy](https://github.com/kensiprell/grails-drools/blob/master/grails-app/services/grails/plugin/drools/DroolsService.groovy)

Ken

**Comment by lvazquezt** [comment]
Hi,

The facts are not persisted in the database that's why I didn't put them there.

I had the Drools project working perfectly before but when moving to Grails, I couldn't manage to make Drools find the kmodule.xml file and I thought the plugin was a good option. I use DroolsConfig.groovy to set up the kbase and session.

Lino

**Comment by lvazquezt** [comment]
Hi,

The facts are not persisted in the database that's why I didn't put them there.

I had the Drools project working perfectly before but when moving to Grails, I couldn't manage to make Drools find the kmodule.xml file and I thought the plugin was a good option. I use DroolsConfig.groovy to set up the kbase and session.

Lino

**Comment by kensiprell** [comment]
I think you are ok without putting your facts in `grails-app/domain`, but I can't tell from your comments so far if `package/member__I` refers to a rule or a fact.

* Are your rule files in a jar, or are they flat files? 

* Where are your rule files located in reference to your application's root directory, and how is it structured?

* What does `ArrayList<Objects> facts` contain when the error message appears? 

* Are the facts the same when it does not error? 

Ken

**Comment by lvazquezt** [comment]
Hello,

I have a 'package/Member' class. 'package/member__I' doesn't exists, that's why I am a bit confused. Might be a reference that Grails generates on its own.

*My rules are in flat files

*The rules are in "\src\resources\rules\rules2012"

*Nothing. It happens before I call the method. That is why I put that it shows up at compilation time.

*As said, there are no facts, but if I execute the output is the same with error and without.

Lino

**Comment by kensiprell** [comment]
Lino reported:  I did a bit of refactoring so I don't have 2 classes named the same way and it's gone. My theory is that is a problem on how Grails generates internal names for classes and Domain class objects. Is not good practice to have two classes named the same way so no problem changing it. I'll let you know if I discover something new about it.
